name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 # You can change the Node.js version if needed

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build # Adjust the build command if needed

    - name: Get Vercel Environment Variables
      run: |
        npx vercel env pull --token ${{ secrets.VERCEL_TOKEN }} --prod
      env:
        VERCEL_ENV: production

    - name: Deploy to Vercel
      run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --scope shrestha-tripathi --project ai-toolkit

